Modify/create tournament button
Kendoers/Kendo-tournament-app pull request #61
Opened 2024-04-19 13:48 UTC by tktstudent

Updating button

2024-04-22 06:14 UTC, pinskii requested changes
Nappi menee nyt mobiilissa piiloon tonne korttien taakse
![image](https://github.com/Kendoers/Kendo-tournament-app/assets/145121433/a66b1688-dbec-42b5-8e19-f243c82652ee)

2024-04-22 06:14 UTC, pinskii commented on frontend/src/components/modules/Tournaments/TournamentListing/TournamentsList.tsx
> +          backgroundColor: "red",
Tän värin vois muuttaa samaks ku kaikki muut punaset meillä on

2024-04-23 15:16 UTC, pinskii commented on frontend/src/components/modules/Tournaments/TournamentListing/TournamentsList.tsx
> +            transform: "translateY(-5%)"
Onks tää + tarkotuksella haluttu oleen vähän ylempänä keskeltä? Mietin vaan et onko jääny vahingossa vai halusitko tän sen näköseks

2024-04-23 15:22 UTC, tktstudent commented on frontend/src/components/modules/Tournaments/TournamentListing/TournamentsList.tsx
> +            transform: "translateY(-5%)"
<img width="238" alt="Näyttökuva 2024-04-23 kello 18 19 14" src="https://github.com/Kendoers/Kendo-tournament-app/assets/96294790/ec6b21ac-e889-4833-975e-41a8d6d7f37b">
se aluks näytti ainaki mulla että se "+" ois vähä alhaal, nii nostin sit sitä 5% ylemmäs ja koitin muutenki tehä tosta pallosta vielä pyörempää.
<img width="218" alt="Näyttökuva 2024-04-23 kello 18 19 33" src="https://github.com/Kendoers/Kendo-tournament-app/assets/96294790/13326cee-f6b5-4aea-9481-10e1b8773c1c">
, näyttääks se sulla miltä?

2024-04-23 15:24 UTC, pinskii commented on frontend/src/components/modules/Tournaments/TournamentListing/TournamentsList.tsx
> +            transform: "translateY(-5%)"
Näyttää et ois vähän ylempänä keskeltä, suunnilleen ton verran ku toi sun eka kuva on alempana

2024-04-23 15:26 UTC, tktstudent commented on frontend/src/components/modules/Tournaments/TournamentListing/TournamentsList.tsx
> +            transform: "translateY(-5%)"
okei, voin käydä kohta ottaan sen ton 5% noston pois

2024-04-23 15:29 UTC, pinskii commented on frontend/src/components/modules/Tournaments/TournamentListing/TournamentsList.tsx
> +            transform: "translateY(-5%)"
okei joo, paha sanoo miltä se tulee näyttään sit siellä servulla ku nyt näyttää niin erilaisilta meillä 😄 mut ilman sitä sen pitäs teoriassa olla keskellä

2024-04-29 11:43 UTC, pinskii approved these changes

2024-04-29 11:43 UTC, merged